name: earthquake
description: Earthquake is an app created to show earthquakes in real time. created to be user friendly with dynamic filters. Is fast and stable. We show earthquakes from 1980 till now. Activate notification to get real time notifications for your grup of filters.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+3
  http: 0.12.0+4
  flutter_stetho: ^0.5.2
  intl: ^0.16.1
  device_info: ^0.4.2+1
  lazy_load_scrollview: ^1.0.1
  loadany: ^0.1.3
  flag: ^1.0.3
  country_pickers: ^1.2.0
  timeago: ^2.0.26
  flutter_map: ^0.8.2
  searchable_dropdown: ^1.1.3
  flutter_map_marker_cluster: ^0.2.7
  latlong: ^0.6.1
  geolocator: ^5.3.1
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.0
  #dash_chat: ^1.0.18
  flutter_device_type: ^0.2.0
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  flutter_launcher_name: ^0.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  image: assets/sc.png
  color: "00ADEF"
  android_disable_fullscreen: true

flutter_launcher_name:
  name: "Earthquake"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/tsunami.png
    - assets/logo.png
    - assets/logod.png
    - assets/sc.png
    - assets/no_internet.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
